# Generated by Django 5.2.5 on 2025-08-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField()),
                ('application_link', models.URLField()),
                ('application_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deadline_undergrad', models.DateField(blank=True, null=True)),
                ('deadline_grad', models.DateField(blank=True, null=True)),
                ('scholarship_info', models.TextField(blank=True)),
                ('course_offered', models.CharField(max_length=200)),
            ],
        ),
    ]
