# Generated by Django 5.2.5 on 2025-08-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='degree_level',
            field=models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('both', 'Both')], default='both', max_length=20),
        ),
    ]
