# Generated by Django 5.2.5 on 2025-09-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_degree_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='website',
            new_name='university_link',
        ),
        migrations.RemoveField(
            model_name='university',
            name='course_offered',
        ),
        migrations.RemoveField(
            model_name='university',
            name='degree_level',
        ),
        migrations.RemoveField(
            model_name='university',
            name='scholarship_info',
        ),
        migrations.AddField(
            model_name='university',
            name='bachelor_programs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='university',
            name='masters_programs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='university',
            name='scholarships',
            field=models.JSONField(default=list),
        ),
    ]
