# Generated by Django 5.2.5 on 2025-09-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_rename_website_university_university_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='course_offered',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
