# Generated by Django 5.2.5 on 2025-09-16 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_university_course_offered'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.ManyToManyField(blank=True, related_name='accepted_by', to='universities.university')),
                ('applied', models.ManyToManyField(blank=True, related_name='applied_by', to='universities.university')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited_by', to='universities.university')),
                ('planning_to_apply', models.ManyToManyField(blank=True, related_name='planned_by', to='universities.university')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to=settings.AUTH_USER_MODEL)),
                ('visa_approved', models.ManyToManyField(blank=True, related_name='visa_approved_for', to='universities.university')),
            ],
        ),
    ]
