# Generated by Django 5.2.5 on 2025-09-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_userdashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboard',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdashboard',
            name='subscription_status',
            field=models.CharField(choices=[('none', 'None'), ('active', 'Active'), ('expired', 'Expired')], default='none', max_length=10),
        ),
    ]
