# Generated by Django 5.2.5 on 2025-09-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_userdashboard_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboard',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
